MyCms/Areas/Admin/Controllers/ManageRoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyCms.Areas.Admin.Controllers
{
    [Authorize(Roles = "Owner")]
    [Area("Admin")]
    public class ManageRoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public ManageRoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        #region Index
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }
        #endregion

        #region AddRole
        [HttpGet]
        public IActionResult AddRole()
        {
            return View();
        }
        #endregion

        #region AddRole [HttpPost]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRole(string name)
        {
            if (string.IsNullOrEmpty(name))
            {
                return NotFound("Error 404  NotFound");
            }

            var role = new IdentityRole(name);
            var result = await _roleManager.CreateAsync(role);

            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(role);
        }
        #endregion

        #region Delete
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("Error 404  NotFound");
            }
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound("Error 404  NotFound");
            }
            return View(role);
        }
        #endregion

        #region Delete [HttpPost]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRole(string itemid)
        {
            if (string.IsNullOrEmpty(itemid))
            {
                return NotFound("Error 404  NotFound");
            }
            var role = await _roleManager.FindByIdAsync(itemid);
            if (role == null)
            {
                return NotFound("Error 404  NotFound");
            }

            var result = await _roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(role);
        }
        #endregion

    }
}

MyCms/Areas/Admin/Controllers/PageGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer;
using Microsoft.AspNetCore.Authorization;

namespace MyCms.Areas.Admin.Controllers
{
    [Authorize(Roles = "Owner")]
    [Area("Admin")]
    public class PageGroupsController : Controller
    {
        private readonly IGroupRepository _GroupRepository;

        public PageGroupsController(IGroupRepository groupRepository)
        {
            _GroupRepository = groupRepository;
        }

        #region Index
        // GET: Admin/PageGroups
        public async Task<IActionResult> Index()
        {
            return await Task.Run(() =>
            {
                return View(_GroupRepository.GetAllGroups());
            });           
        }
        #endregion

        #region Create
        // GET: Admin/PageGroups/Create
        public IActionResult Create()
        {
            return View();
        }
        #endregion

        #region Create [HttpPost]
        // POST: Admin/PageGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GroupID,GroupName")] Group pageGroup)
        {
            if (ModelState.IsValid)
            {
                return await Task.Run(() => 
                {
                    _GroupRepository.InsertGroup(pageGroup);
                    _GroupRepository.save();
                    return RedirectToAction(nameof(Index));
                });

            }
            return View(pageGroup);
        }
        #endregion

        #region Edit
        // GET: Admin/PageGroups/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Group Group =_GroupRepository.GetGroupById(id.Value);
            if (Group == null)
            {
                return NotFound();
            }
            return View(Group);
        }
        #endregion

        #region Edit [HttpPost]
        // POST: Admin/PageGroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GroupID,GroupName")] Group Group)
        {
            if (id != Group.GroupID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                return await Task.Run(() =>
                {
                    _GroupRepository.UpdateGroup(Group);
                    _GroupRepository.save();
                    return RedirectToAction(nameof(Index));
                });
            }
            return View(Group);
        }
        #endregion

        #region Delete
        // GET: Admin/PageGroups/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Group Group = _GroupRepository.GetGroupById(id.Value);

            if (Group == null)
            {
                return NotFound();
            }

            return View(Group);
        }
        #endregion

        #region DeleteConfirmed HttpPost
        // POST: Admin/PageGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _GroupRepository.DeleteGroup(id);
            _GroupRepository.save();
            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region Dispose
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _GroupRepository.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

MyCms/Areas/Admin/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;


namespace MyCms.Areas.Admin.Controllers
{
    [Authorize(Roles = "Owner,Publisher")]
    [Area("Admin")]
    public class PagesController : Controller
    {
        private IPageRepository _PageRepository;
        private IGroupRepository _GroupRepository;

        public PagesController(IPageRepository PageRepository,
                               IGroupRepository GroupRepository)
        {
            _PageRepository = PageRepository;
            _GroupRepository = GroupRepository;
        }
        #region Index
        // GET: Admin/Pages
        public IActionResult Index(string publisher)
        {
            if (User.IsInRole("Owner"))
            {
                return View(_PageRepository.GetAllPages());
            }
            publisher = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(_PageRepository.GetPublisherPage(publisher));
        }
        #endregion

        #region Create
        // GET: Admin/Pages/Create
        public IActionResult Create()
        {
            ViewBag.GroupID = new SelectList(_GroupRepository.GetAllGroups(), "GroupID", "GroupName");
            return View();
        }
        #endregion

        #region Create [HttpPost]
        // POST: Admin/Pages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("PageID,GroupID,Publisher,PublisherID,PageTitle,ShortDescription,Text,ImageFile,ShowInSlider,View,CreateDate,Tags,ImageName")] Page page)
        {
            ModelState.Remove("Publisher");
            ModelState.Remove("PublisherID");
            if (ModelState.IsValid)
            {
                page.View = 0;
                page.CreateDate = DateTime.Now;
                page.Publisher = User.FindFirstValue(ClaimTypes.Name);
                page.PublisherID = User.FindFirstValue(ClaimTypes.NameIdentifier);
                //get file extension
                //FileInfo fileInfo = new FileInfo(page.ImageAddress.FileName);
                if (page.ImageFile != null)
                {
                    string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads");

                    //create folder if not exist
                    if (!Directory.Exists(path)) Directory.CreateDirectory(path);

                    string fileName = Guid.NewGuid() + page.ImageFile.FileName;

                    string fileNameWithPath = Path.Combine(path, fileName);

                    using var stream = new FileStream(fileNameWithPath, FileMode.Create);
                    page.ImageFile.CopyTo(stream);
                    page.ImageName = fileName;
                }
                _PageRepository.InsertPage(page);
                _PageRepository.save();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Create));
        }
        #endregion

        #region Edit
        // GET: Admin/Pages/Edit/5
        public IActionResult Edit(int? id)
        {
            Page page = _PageRepository.GetPagesById(id.Value);
            if (User.IsInRole("Owner") || User.IsInRole("Publisher") && page.PublisherID.Contains(User.FindFirstValue(ClaimTypes.NameIdentifier)))
            {
                ViewBag.GroupID = new SelectList(_GroupRepository.GetAllGroups(), "GroupID", "GroupName");
                if (id == null)
                {
                    return NotFound();
                }
                if (page == null)
                {
                    return NotFound();
                }
                return View(page);
            }
            else
            {
                return BadRequest();
            }
        }
        #endregion

        #region Edit [HttpPost]
        // POST: Admin/Pages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("PageID,GroupID,Publisher,PublisherID,PageTitle,ShortDescription,Text,ImageFile,ShowInSlider,Tags,ImageName,View,CreateDate")] Page page)
        {
            if (id != page.PageID)
            {
                return NotFound();
            }
            if (User.IsInRole("Owner") || User.IsInRole("Publisher") && page.PublisherID.Contains(User.FindFirstValue(ClaimTypes.NameIdentifier)))
            {
                if (ModelState.IsValid)
                {
                    if (User.IsInRole("Publisher"))
                    {
                        page.Publisher = User.FindFirstValue(ClaimTypes.Name);
                        page.PublisherID = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    }
                    if (page.ImageFile != null)
                    {
                        string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads");

                        //create folder if not exist
                        if (!Directory.Exists(path)) Directory.CreateDirectory(path);

                        if (page.ImageName != null)
                        {
                            System.IO.File.Delete("wwwroot/uploads/" + page.ImageName);
                        }
                        string fileName = Guid.NewGuid() + page.ImageFile.FileName;

                        string fileNameWithPath = Path.Combine(path, fileName);

                        using var stream = new FileStream(fileNameWithPath, FileMode.Create);
                        page.ImageFile.CopyTo(stream);
                        page.ImageName = fileName;
                    }

                    _PageRepository.UpdatePage(page);
                    _PageRepository.save();
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                return BadRequest();
            }
            return RedirectToAction(nameof(Edit));
        }
        #endregion

        #region Delete
        // GET: Admin/Pages/Delete/5
        public IActionResult Delete(int? id)
        {
            Page page = _PageRepository.GetPagesById(id.Value);
            if (User.IsInRole("Owner"))
            {
                if (id == null)
                {
                    return NotFound();
                }
                if (page == null)
                {
                    return NotFound();
                }
                return View(page);
            }
            if (User.IsInRole("Publisher") && page.Publisher.Contains(User.FindFirstValue(ClaimTypes.Name)))
            {
                return View(page);
            }
            else
            {
                return BadRequest();
            }
        }
        #endregion

        #region Delete [HttpPost]
        // POST: Admin/Pages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var page = _PageRepository.GetPagesById(id);
            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads");
            if (page.ImageName != null)
            {
                System.IO.File.Delete(Path.Combine(path, page.ImageName));
            }
            _PageRepository.DeletePage(id);
            _PageRepository.save();
            return RedirectToAction(nameof(Index));
        }
        #endregion

        #region Dispose
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _PageRepository.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

MyCms/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=0.75" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-rtl.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/StylesAdmin.css" />
    <link rel="stylesheet" href="~/css/navbar_items.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>    
    <script src="/ckeditor/ckeditor.js"></script>
    <title>MyCms</title>
</head>
<body>
    <nav class="navbar navbar-toggleable-sm navbar-dark shadow-lg">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3 text-dark d-none d-lg-block">پنل مدیریت</a>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between container">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item dropdown d-block d-lg-none">                        
                        <a class="nav-link dropdown-toggle text-dark text-right" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="true">@User.Identity.Name - پنل مدیریت</a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-items-right">
                        @if (User.IsInRole("Owner") || User.IsInRole("Manager") || User.IsInRole("Publisher"))
                        {
                            @if (User.IsInRole("Owner") || User.IsInRole("Publisher"))
                            {
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Pages" asp-action="Index">خبر ها</a>
                            }
                            @if (User.IsInRole("Owner"))
                            {
                                <a class="dropdown-item" asp-area="Admin" asp-controller="PageGroups" asp-action="Index">گروه های خبری</a>
                                <a class="dropdown-item " asp-area="Admin" asp-controller="ManageRole" asp-action="Index"> مقام ها</a>
                            }
                            @if (User.IsInRole("Owner") || User.IsInRole("Manager"))
                            {
                                <a class="dropdown-item" asp-area="Admin" asp-controller="ManageUser" asp-action="Index"> کاربران</a>
                            }
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">خانه</a>
                        }
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav-nav">
            <nav class="collapse d-lg-block sidebar sb-sidenav sb-sidenav-light alert-secondary shadow-lg sidebar-padding" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading ">@User.FindFirstValue(ClaimTypes.Role)</div>
                        @if (User.IsInRole("Owner") || User.IsInRole("Manager") || User.IsInRole("Publisher"))
                        {

                            @if (User.IsInRole("Owner") || User.IsInRole("Publisher"))
                            {
                                <a class="nav-link" asp-area="Admin" asp-controller="Pages" asp-action="Index">
                                    <div class="sb-nav-link-icon"></div>
                                    خبر ها
                                </a>
                            }
                            @if (User.IsInRole("Owner"))
                            {
                                <a class="nav-link" asp-area="Admin" asp-controller="PageGroups" asp-action="Index">
                                    <div class="sb-nav-link-icon"></div>
                                    گروه های خبری
                                </a>
                                <a class="nav-link" asp-area="Admin" asp-controller="ManageRole" asp-action="Index">
                                    <div class="sb-nav-link-icon"></div>
                                    مقام ها
                                </a>
                            }
                            @if (User.IsInRole("Owner") || User.IsInRole("Manager"))
                            {
                                <a class="nav-link" asp-area="Admin" asp-controller="ManageUser" asp-action="Index">
                                    <div class="sb-nav-link-icon"></div>
                                    کاربران
                                </a>
                            }

                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <div class="sb-nav-link-icon"></div>
                                بازگشت به خانه
                            </a>

                        }
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">کاربر وارد شده:</div>
                    @User.Identity.Name
                </div>
            </nav>
        </div>
        <div class="container ">
            <main role="main" class="pb-3 align-content-end">
                <div>
                    <div>
                        @RenderBody()
                    </div>
                </div>
            </main>
            <footer class="py-4 mt-auto border-top">
                <div class="container-fluid px-4">                   
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">&copy; 1402 - MyCmsWebApplication - Asp.Net Core Mvc</div>
                        <div class="left-side">
                        <h4><a href="">BRAND LOGO</a></h4>
                        <H6> Place Holder</H6>
                    </div>
                    </div>
                </div>
                <br />
            </footer>
        </div>
    </div>
    <script src="/js/scripts.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script src="/ckeditor/ckeditor.js"></script>
<script src="/ckeditor/adapters/jquery.js"></script>

MyCms/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyCms</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-rtl.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
            <div class="container">
                <a class="navbar-brand">پنل مدیریت</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    @if (User.IsInRole("Owner") || User.IsInRole("Manager") || User.IsInRole("Publisher"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">خانه</a>
                            </li>

                            @if (User.IsInRole("Owner") || User.IsInRole("Publisher"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Pages" asp-action="Index">خبر ها</a>
                                </li>
                            }
                            @if (User.IsInRole("Owner"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="PageGroups" asp-action="Index">گروه های خبری</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="ManageRole" asp-action="Index">مدیریت مقام ها</a>
                                </li>
                            }
                            @if (User.IsInRole("Owner") || User.IsInRole("Manager"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="ManageUser" asp-action="Index">مدیریت کاربران</a>
                                </li>
                            }

                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 1402 - MyCms - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script src="/ckeditor/ckeditor.js"></script>
<script src="/ckeditor/adapters/jquery.js"></script>
<script src="/ckeditor/CkeditorFile.jsx"></script>
@*<script>
    $(function () {
    $('#Text').ckeditor();
    });
    </script>*@