MyCms/Areas/Admin/Controllers/ManageUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyCms.Areas.Admin.Controllers
{
    [Authorize(Roles = "Owner")]
    [Area("Admin")]
    public class ManageUserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ManageUserController(UserManager<IdentityUser> userManager,
                                    RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        #region Index
        [HttpGet]
        public IActionResult Index()
        {
            var model = _userManager.Users.Select(u => new IndexViewModel()
            {
                Id = u.Id,
                UserName = u.UserName,
                Email = u.Email,
                IsEmailConfirmed = u.EmailConfirmed

            }).ToList();

            return View(model);
        }
        #endregion

        #region EditUser
        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("Error 404  NotFound");
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound("Error 404  NotFound");
            }
            return View(user);
        }
        #endregion

        #region EditUser [HttpPost]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> EditUser(string id, string username, RoleForUserViewModel model)
        {
            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(username))
            {
                return NotFound("Error 404  NotFound");
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound("Error 404  NotFound");
            }
            user.UserName = username;
            var result = await _userManager.UpdateAsync(user);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(result);
        }
        #endregion

        #region AddRoleForUser
        [HttpGet]
        public async Task<IActionResult> AddRoleForUser(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("Error 404  NotFound");
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound("Error 404  NotFound");
            }
            var roles = _roleManager.Roles.ToList();
            var model = new RoleForUserViewModel() { UserId = id };

            foreach (var role in roles)
            {
                if (!await _userManager.IsInRoleAsync(user, role.Name))
                {
                    model.UserRoles.Add(new UserRolesViewModel()
                    {
                        RoleName = role.Name
                    });

                }
            }
            return View(model);
        }
        #endregion

        #region AddRoleForUser [HttpPost]
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> AddRoleForUser(RoleForUserViewModel model)
        {
            if (model == null)
            {
                return NotFound("Error 404  NotFound");
            }
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null)
            {
                return NotFound("Error 404  NotFound");
            }
            var requestRoles = model.UserRoles.Where(r => r.IsSelected)
                .Select(u => u.RoleName)
                .ToList();
            var result = await _userManager.AddToRolesAsync(user, requestRoles);

            if (result.Succeeded)
            {
                return RedirectToAction("index");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }
        #endregion

        #region RemoveRoleFromUser
        [HttpGet]
        public async Task<IActionResult> RemoveRoleFromUser(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("Error 404  NotFound");
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound("Error 404  NotFound");
            }
            var roles = _roleManager.Roles.ToList();
            var model = new RoleForUserViewModel() { UserId = id };

            foreach (var role in roles)
            {
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    model.UserRoles.Add(new UserRolesViewModel()
                    {
                        RoleName = role.Name
                    });
                }
            }

            return View(model);
        }
        #endregion

        #region RemoveRoleFromUser
        [HttpPost]
        public async Task<IActionResult> RemoveRoleFromUser(RoleForUserViewModel model)
        {
            if (model == null)
            {
                return NotFound("Error 404  NotFound");
            }
            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null)
            {
                return NotFound("Error 404  NotFound");
            }
            var requestRoles = model.UserRoles.Where(r => r.IsSelected)
                .Select(u => u.RoleName)
                .ToList();
            var result = await _userManager.RemoveFromRolesAsync(user, requestRoles);

            if (result.Succeeded) return RedirectToAction("index");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }
        #endregion

        #region DeleteUser
        [HttpGet]
        public async Task< IActionResult> DeleteUser(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("Error 404  NotFound");
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound("Error 404  NotFound");
            }
            return View(user);
        }
        #endregion

        #region DeleteUser [HttpPost]
        [HttpPost, ActionName("DeleteUser")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUserConfirmed(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound("Error 404  NotFound");
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound("Error 404  NotFound");
            }
            await _userManager.DeleteAsync(user);

            return RedirectToAction("Index");
        }
        #endregion
    }
}

MyCms/Areas/Admin/Views/ManageUser/AddRoleForUser.cshtml
@model RoleForUserViewModel

<br />
<ol class="breadcrumb">
    <li class="breadcrumb-item active">خانه / </li>
    <li class="breadcrumb-item active">پنل مدیریت</li>
    <li class="breadcrumb-item active">کاربران</li>
     <li class="breadcrumb-item active">افزودن مقام </li>
</ol>
<hr />

@if (!Model.UserRoles.Any())
{
    <h5>هیچ مقامی یافت نشد</h5>
}
else
{
    <form asp-controller="ManageUser" asp-action="AddRoleForUser" method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>

        @for (int i = 0; i < Model.UserRoles.Count; i++)
        {
        <div class="form-group">
            <input asp-for="@Model.UserRoles[i].IsSelected" />
            <label>@Model.UserRoles[i].RoleName</label>

            <input type="hidden" asp-for="@Model.UserRoles[i].RoleName" />
        </div>
        }
        <input type="hidden" asp-for="@Model.UserId" />
        <a class="btn btn-outline-secondary" href="/Admin/ManageUser">بازگشت</a>
        <button class="btn btn-success" type="submit">ثبت</button>
    </form>
}

MyCms/Areas/Admin/Views/ManageUser/DeleteUser.cshtml
@model Microsoft.AspNetCore.Identity.IdentityUser

@{
    ViewData["Title"] = "DeleteUser";
}
<br />
<ol class="breadcrumb">
    <li class="breadcrumb-item active">خانه / </li>
    <li class="breadcrumb-item active">پنل مدیریت</li>
    <li class="breadcrumb-item active">کاربران</li>
    <li class="breadcrumb-item active">حذف کاربر</li>
</ol>
<hr />
<form asp-controller="ManageUser" asp-action="DeleteUser" method="post" >
    <h6 class="mt-2">@Model.UserName</h6>
    <p>آیا میخواهید این کاربر حذف شود؟</p>
    <a class="btn btn-sm btn-outline-secondary" href="/Admin/ManageUser">بازگشت</a>
    <button type="submit" class="btn btn-sm btn-outline-danger">حذف کاربر</button>
</form>

MyCms/Areas/Admin/Views/ManageUser/EditUser.cshtml
@model Microsoft.AspNetCore.Identity.IdentityUser
@{
    ViewData["Title"] = "EditUser";
}

<br />
<ol class="breadcrumb">
    <li class="breadcrumb-item active">خانه / </li>
    <li class="breadcrumb-item active">پنل مدیریت</li>
    <li class="breadcrumb-item active">کاربران</li>
     <li class="breadcrumb-item active">ویرایش کاربر</li>
</ol>
<hr />
<form asp-controller="ManageUser" asp-action="EditUser" method="post">
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
    <div class="form-group">
        <label class="control-lable" asp-for="UserName">نام کاربر :</label>
        <input class="form-control" asp-for="UserName" />
    </div>
    <input type="hidden" asp-for="Id" />
    <a class="btn btn-outline-secondary" href="/Admin/ManageUser">بازگشت</a>
    <button class="btn btn-success" type="submit">ثبت</button>
</form>

MyCms/Areas/Admin/Views/ManageUser/Index.cshtml
@model List<IndexViewModel>

<br />
<ol class="breadcrumb">
    <li class="breadcrumb-item active">خانه / </li>
    <li class="breadcrumb-item active">پنل مدیریت</li>
    <li class="breadcrumb-item active">کاربران</li>
</ol>
<hr />
<div class="row col-12 text-center d-flex justify-content-center">
    @if (!Model.Any())
    {
        <h1>کاربری یافت نشد</h1>
    }
    else
    {
        for (int i = 0; i < Model.Count; i++)
        {

            <div class="card border-light col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div class="card-body">
                    نام کاربر : <b>@Model[i].UserName</b>
                    <hr />
                    ایمیل : <b>@Model[i].Email</b>
                    <hr />
                    تایید ایمیل : <b>@Model[i].IsEmailConfirmed</b>
                </div>
                <div>                    
                    <a asp-controller="ManageUser" asp-action="EditUser" asp-route-id="@Model[i].Id" class="btn btn-sm btn-outline-secondary">ویرایش</a>

                    <a asp-controller="ManageUser" asp-action="AddRoleForUser" asp-route-id="@Model[i].Id" class="btn btn-sm btn-outline-secondary">افزودن مقام</a>

                    <a asp-controller="ManageUser" asp-action="RemoveRoleFromUser" asp-route-id="@Model[i].Id" class="btn btn-sm btn-outline-danger">حذف مقام</a>

                    <a asp-controller="ManageUser" asp-action="DeleteUser" asp-route-id="@Model[i].Id" class="btn btn-sm btn-outline-danger">حذف کاربر </a>
                </div>
            </div>

        }

    }
</div>

MyCms/Areas/Admin/Views/ManageUser/RemoveRoleFromUser.cshtml
@model RoleForUserViewModel

@{
    ViewData["Title"] = "RemoveRoleFromUser";
}
<br />
<ol class="breadcrumb">
    <li class="breadcrumb-item active">خانه / </li>
    <li class="breadcrumb-item active">پنل مدیریت</li>
    <li class="breadcrumb-item active">کاربران</li>
     <li class="breadcrumb-item active">حذف مقام</li>
</ol>
<hr />
<form asp-controller="ManageUser" asp-action="RemoveRoleFromUser" method="post">
    <div class="text-danger" asp-validation-summary="ModelOnly"></div>
    @if (!Model.UserRoles.Any())
    {        
        <h5>هیچ مقامی یافت نشد</h5>
        <a class="btn btn-outline-secondary" href="/Admin/ManageUser">بازگشت</a>
    }
    else
    {
        for (int i = 0; i < Model.UserRoles.Count; i++)
        {
            <div class="form-group">
                <input asp-for="@Model.UserRoles[i].IsSelected" />
                <label>@Model.UserRoles[i].RoleName</label>

                <input type="hidden" asp-for="@Model.UserRoles[i].RoleName" />
            </div>
        }
        <a class="btn btn-outline-secondary" href="/Admin/ManageUser">بازگشت</a>
        <button class="btn btn-danger" type="submit">حذف</button>
    }

    <input type="hidden" asp-for="@Model.UserId" />
    
    
</form>